import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { expect, test } from "./fixtures/consoleProcess";
import { expectNoSeriousAccessibilityViolations } from "./accessibility";

test("record context and expanded responses stay readable with long nested skill names", async ({ page, consoleProcess }, testInfo) => {
  await page.setViewportSize({ width: 1920, height: 1080 });
  const fixture = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../../../loomspan-console-fixtures/traces/current-plan-semantic-evidence.ndjson");
  const skill = "hotelSelectionWithAnIntentionallyLongSkillName";
  const trace = fs.readFileSync(fixture, "utf8").replaceAll("shared.skill", skill);
  await page.goto(consoleProcess.pairingUrl);
  await page.goto(`${consoleProcess.origin}/trace-storage`);
  await page.getByLabel("Trace files").setInputFiles({ name: "context.ndjson", mimeType: "application/x-ndjson", buffer: Buffer.from(trace) });
  await expect(page.getByRole("heading", { name: "Trace explorer" })).toBeVisible();
  await page.getByRole("tab", { name: "Records", exact: true }).click();
  const table = page.getByRole("region", { name: "Record list", exact: true });
  await expect(table.getByRole("columnheader", { name: "Context", exact: true })).toBeVisible();
  const row = table.locator("#trace-record-27");
  const context = `${skill} → ${skill} / Planning`;
  await expect(row.getByRole("cell", { name: `${skill} / Planning`, exact: true })).toBeVisible();
  const trigger = row.locator(".trace-context-trigger");
  await trigger.hover();
  await expect(page.getByRole("tooltip")).toHaveText(context);
  await page.keyboard.press("Escape");
  await expect(page.getByRole("tooltip")).toHaveCount(0);
  await page.mouse.move(0, 0);
  await row.focus();
  await page.keyboard.press("Tab");
  await expect(trigger).toBeFocused();
  await expect(page.getByRole("tooltip")).toHaveText(context);
  await page.screenshot({ path: testInfo.outputPath("record-context-tooltip.png") });
  await page.keyboard.press("Escape");
  await expect(page.getByRole("tooltip")).toHaveCount(0);
  await expect(row).not.toContainText("planning-nested");
  await row.getByRole("button", { name: "Response", exact: true }).click();
  const detail = page.getByRole("region", { name: "Model response for record 27", exact: true });
  await expect(detail.getByRole("heading", { name: context, exact: true })).toBeVisible();
  await expect(detail).toContainText("fixture response");
  await row.scrollIntoViewIfNeeded();
  await page.screenshot({ path: testInfo.outputPath("record-context-desktop.png") });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.emulateMedia({ forcedColors: "active" });
  const cell = row.locator(".trace-record-context");
  await cell.scrollIntoViewIfNeeded();
  await expect(cell).toBeInViewport();
  expect(await cell.evaluate((element) => element.scrollWidth <= element.clientWidth + 1)).toBe(true);
  await expectNoSeriousAccessibilityViolations(page);
  await page.screenshot({ path: testInfo.outputPath("record-context-narrow.png") });
  await row.getByRole("button", { name: "Read raw record", exact: true }).click();
  await expect(page.getByRole("region", { name: "Raw record 27", exact: true })).toContainText("planning-nested");
});
